---
title: "cleaned_code"
output: html_document
---

```{r}
library(sf)
library(dplyr)
# devtools::install_github("beanumber/macleish")
#install.packages("macleish")
library(macleish)
library(tidyverse)
library(leaflet)
```

Add length column:
```{r}
trails %>% 
group_by(name) %>% 
summarise(Num_segments = n(), 
          total_length = sum(computed_length)) %>%
arrange(total_length)
```

Change crs of trails: Maybe not needed??
```{r}
trails_4326 <- trails %>%
  st_transform(4326)
trails_4326
```

Test drawing trails:
```{r}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolylines(data = trails_4326)
```

Get contour data:
```{r}
url <- "http://download.massgis.digital.mass.gov/shapefiles/state/contours250k.zip"
local_file <- basename(url)
download.file(url, destfile = local_file)
unzip(local_file, exdir = "contours")
```

Make contours_elevation file
```{r}
library(sf)
dsn <- path.expand("contours")
contours_elevation <- read_sf(dsn)
```

Check crs and projections...
```{r}
st_crs(contours_elevation)
contours_4326 <- st_transform(contours_elevation, 4326)
st_crs(contours_4326)
```

Restrict contours to macleish
```{r}
Boundary_contours <- st_intersection(st_as_sf(macleish_layers[["boundary"]]), contours_4326)

leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["boundary"]])%>%
  addPolylines(data = Boundary_contours) %>%
  addPolylines(data = macleish_layers[["trails"]], color= "brown")
```

Test with just "Porcupine Trail:"
```{r}
porcupine <- st_as_sf(macleish_layers[["trails"]]) %>%
  filter(name == "Porcupine Trail") %>%
  mutate(computed_length = st_length(geometry)) 

leaflet() %>%
  addTiles() %>%
  addPolylines(data = macleish_layers[["boundary"]])%>%
  addPolylines(data = Boundary_contours) %>%
  addPolylines(data = porcupine, color= "brown")

```

#for each geometry set in the linestring, match with contour line geometry to give FT?
